### ISSUE TITLE
Working for Gnome 42

### ISSUE THREAD

**Issue by jvonhoff** [will/bgwinch.nvim#1]
I'm a Neovim noob, but I think I've gotten light/dark switching on Arch Linux and Gnome 42 using gnome-terminal.  I thought I'd throw the steps here, in case it could help others.

1. Install this plugin - [will/bgwinch.nvim](https://github.com/will/bgwinch.nvim)
2. Make sure that your Neovim theme changes back & forth (light/dark) when you run (in Neovim) ```:set background=light``` (or dark).  I use TokyoNight, and that works.
3. In Gnome Shell, install the [Night Theme Switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/) extension
4. Verify that NTS works by changing to dark mode with the Night Theme Switcher.  Your gnome-terminal (without Neovim running) should alternate between a dark & light background.  If not, you might need to set your gnome-terminal profile to "use colors from system theme".
5. In NTS settings, set something in Commands for Sunrise & Sunset. I use a script that I call with the parameter "light" for Sunrise, and "dark" for Sunset. Regardless, the important part of what my script does is ```echo $1 > /dev/shm/theme``` to set "light" or "dark" into this /dev/shm/theme file, and finally also calls ```killall -SIGWINCH nvim``` to pass the signal over to Neovim when we flip between light/dark.
6. Now, in your Neovim config, add a lua block like:
```
local bgwinch = require "bgwinch"
local Job = require "plenary.job"
bgwinch.setup({set_bg = function()
  local j = Job:new { command = "cat" , args = { "/dev/shm/theme" } }
  j:sync()
  vim.o.background = j:result()[1]
end
})
```
7. Now, start Neovim.  If Neovim is already dark, flip NTS to light mode, and see if it updates Neovim to use a light background.

Troubleshooting:
- you can spoof the SIGWINCH by resizing the gnome-terminal window
- if ```set background=light``` doesn't do anything, then neither will this plugin.  You have to make sure your theme is dark/light ready.
- my script is particular about setting "light" and "dark" -- if you use "Light" or "DarkMode" or something, you'll have to tweak the ```vim.o.background``` part of the lua block in #6 above.

**Comment by will** [comment]
That looks all reasonable to me. Great work figuring that all out! 

I just set up the wiki and made a Gnome page. https://github.com/will/bgwinch.nvim/wiki/Gnome I think that might be easier for people to find than the issues? I'll link it from the readme if you want to move the guide there.

**Comment by jvonhoff** [comment]
Thanks, and thanks also for the Neovim plugin... honestly, I doubt I'd have even known it was possible without seeing your plugin.

But, yes, I think the wiki makes good sense. I wasn't able to see an edit link or anything like that, though, so I'm not sure how to edit the wiki. Do I have to be a maintainer or something like that?

**Comment by will** [comment]
Ok try now, maybe I found the permissions setting.

Ever since neovim added lua, it's really opened up what's possible I think. I mean I _guess_ you could do all this stuff with vimscript before, but I for sure never bothered to write anything for myself. But now it's been honestly kinda fun to make it exactly what I want. Glad you were able to find this and it helped you too.

**Comment by jvonhoff** [comment]
Done... and thanks again!
